controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
app_profile_upload_picture:
  path: '/app/myprofile/upload-picture'
  controller: App\Controller\ProfileController::uploadPicture
